name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '*.md'
  schedule:
    - cron: "0 */6 * * *" # every 6 hours

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Check out code (into the Go module directory)
      uses: actions/checkout@v2
    - name: Build
      run: ./build.sh
    - name: Test
      run: go test -v ./...

  deploy_site:
    name: Deploy Site
    runs-on: ubuntu-18.04
    needs: build
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Check out code (into the Go module directory)
      uses: actions/checkout@v2
    - name: Generate HTML
      run: go run ./cmd/main.go
    - name: Save website artifact
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: web
    - name: Deploy website
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-southeast-2'
        SOURCE_DIR: 'web'